# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cfe8c3e8bb1d85eb7f406acd21fb03ce"
name = "ml-hh-appify"
handle = "ml-hh-appify-1"
application_url = "https://pcs-licenses-importance-thin.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ml-hh-appify.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://pcs-licenses-importance-thin.trycloudflare.com/auth/callback",
  "https://pcs-licenses-importance-thin.trycloudflare.com/auth/shopify/callback",
  "https://pcs-licenses-importance-thin.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
